@extends('layouts.main')
@section('content')
    <div class="row">
        <div class="col-md-12">
        

			    <form method="post" action="http://poll.pollcode.com/78218346">	
			    <div	style="background-color: #EEEEEE; padding: 2px; width: 90%; font-family: Arial; font-size: small; color: #000000;"> <h2>Consultas/ Encuestas </h2><div>	<strong>Planteamiento:</strong> Los vecinos de la Calle Terepaima, ante el incremento de acciones delictivas, han decidido implementar un sistema de seguridad que contempla:</div><div>a) Control de acceso a la calle, a realizarse en dos etapas:</div><div>	<ul>	<li><strong>Etapa 1:</strong> Instalaci&oacute;n de dos rejas ( a ubicar frente a Proud en la parte alta de la calle y detras de la Panader&iacute;a El regreso, en la parte baja de la misma)</li>
<li><strong>Etapa 2:</strong> Construcci&oacute;n de casetas de vigilancia y contrataci&oacute;n de los vigilantes.</li>	</ul></div><div>b) Sistema de monitoreo con la instalaci&oacute;n de un numero determinado de camaras de videovigilancia y centro de control en una de las casetas, articulados con las autoridades de seguridad municipales, estadales y nacionales.</div><div>c) Control de acceso de personas y motos entre Altos de Lebrun y la calle Terepaima, que actualmente se realiza por una escalera y rampa ubicada en la parte media de la calle.</div><br />	<div style="padding: 2px 0px 4px 2px;">	<strong>&iquest;Esta usted de acuerdo con la iniciativa?</strong>	</div>	<input type="radio" name="answer" value="1" id="answer782183461"	style="float: left;" /><label for="answer782183461"	style="float: left; width: 150px;">Si</label>	<div style="clear: both; height: 2px;"></div>	<input type="radio" name="answer" value="2" id="answer782183462"	style="float: left;" /><label for="answer782183462"	style="float: left; width: 150px;">No</label>	<div style="clear: both; height: 2px;"></div>	<div style="padding: 2px 0px 4px 2px;">	<strong>&iquest;Estar&iacute;a dispuesto a contribuir con los costos de inversi&oacute;n y mantenimiento de la iniciativa ?</strong>	</div>	<input type="radio" name="answer" value="1" id="answer782183461"	style="float: left;" /><label for="answer782183461"	style="float: left; width: 150px;">Si</label>	<div style="clear: both; height: 2px;"></div>	<input type="radio" name="answer" value="2" id="answer782183462"	style="float: left;" /><label for="answer782183462"	style="float: left; width: 150px;">No</label>	<div style="clear: both; height: 2px;"></div>	
<div style="padding: 2px 0px 4px 2px;">	<strong>&iquest;Estar&iacute;a de acuerdo, a los fines de reducir las cuotas mensuales, con eliminar los vigilantes de la calle Yaracuy, cuando se cuente con los vigilantes de la calle Terepaima, dejando en la calle unicamente la reja en nuestra calle?</strong>	</div>	<input type="radio" name="answer" value="1" id="answer782183461"	style="float: left;" /><label for="answer782183461"	style="float: left; width: 150px;">Si</label>	<div style="clear: both; height: 2px;"></div>	<input type="radio" name="answer" value="2" id="answer782183462"	style="float: left;" /><label for="answer782183462"	style="float: left; width: 150px;">No</label>	<div style="clear: both; height: 2px;"></div>	
<br/><br/>	<div align="center" style="padding: 3px;">	<input type="submit" value=" Votar ">	</div>
<p>Para mayor informaci&oacute;n al respecto o remisi&oacute;n de ideas o sugerencias agradecemos el env&iacute;o de un correo electr&oacute;nico a : <a href="mailto:buzonasoyaracuy@gmail.com">buzonasoyaracuy@gmail.com</a></p>	</div></form>                                                                                   
        </div>
    </div>
@stop